require:
  - rubocop-factory_bot
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - lib/generators/rails_outbox/templates/*

Gemspec/RequireMFA:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  
RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 2
  
RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 7

RSpec/RemoveConst:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/lib/rails_outbox/outboxable/*

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/lib/rails_outbox/outboxable/*

RSpec/SpecFilePathSuffix:
  Exclude:
    - spec/lib/rails_outbox/outboxable/*
  

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
